name: Code Coverage Report
description: Comments a pull request with the code coverage
author: Romeo Van Snick
branding:
  icon: check-square
  color: green
inputs:
  github-token:
    description: Github token
    required: true
    default: ${{ github.token }}
  lcov-file:
    description: The location of the lcov.info file
    required: false
  lcov-base:
    description: The location of the lcov file for the base branch
    required: false
  filter-changed-files:
    description: Set to true to only comment with coverage on files changed in this commit
    required: false
    default: false
  delete-old-comments:
    description: Set to true to delete old Coverage Report comments
    required: false
    default: false
  working-directory:
    description: Set working directory if project is not in root folder
    required: false
    default: "./"
  title:
    description: Title to add to the comment
    required: false
  diff_threshold:
    description: The minimum coverage (%) the diff must have
    required: false
    default: "85"
  # Exists because API has paging which can be problematic for large PRs
  files_changed:
    description: String of files that have changed from base branch
    required: false
    default: ""
  run_id:
    description: Run id for the current action run
    required: true
    default: "-1"
outputs:
  diff_coverage:
    description: (String - Number) The coverage of this branch
  result:
    description: (String - Boolean) Branch coverage is above coverage threshold (diff_threshold input) or not
runs:
  using: node16
  main: dist/main.js
